[package]
name = "regex_example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
lazy_static = "1.4.0"
log = "0.4.20"
rand = "0.8.5"
rand_distr = "0.4.3"
regex = "1.10.3"
