[package]
name = "harness"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmtime = "17.0.0"
rayon = "1.5.0"
wasmtime-wasi = "17.0.0"

